[package]
name = "octom-server"
version = "0.1.0"
authors = ["Magomed Arsaev <mago@hafven.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
